[[iteration-1]]
= Iteration I

The Iteration-1 is supposed to be the as-is deployment of the __Brewery__ application on to https://kubernetes.io[Kubernetes]
or https://www.openshift.com[Openshift].  This will have all the components from the original https://github.com/spring-cloud-samples/brewery
with modifications required :

- Use the Fabric8 Maven Plugin to generate the Kubernetes/OpenShift resources needed to deploy the applications on the platform
- Design OpenShift templates top deploy RabbitMQ and the different servers such as Eureka, Config-Server, Zipkin, ... (to be discussed)

to have it deployed on to https://kubernetes.io[Kubernetes] or https://www.openshift.com[Openshift]

[[itr1-application-setup]]
== Setup

[[itr1-clone-source]]
=== Clone

[source,sh]
----
git clone -b iteration-1 https://github.com/kameshsampath/brewery
----

[NOTE]
====
Through out this document we will call the directoy where the project was cloned as _$PROJECT_HOME_
====

[[itr1-deployable-apps]]
=== Deploy Applications

.Application List
[cols="1*^,1,1,5"]
|===
| |Application| Folder | Remarks

|icon:check[color: green]
|<<rabbitmq>>
| *$PROJECT_HOME*/extras/rabbitmq
| Message Broker - https://www.rabbitmq.com/

|icon:check[color: green]
|common
|*$PROJECT_HOME*/common
| Common shared library

|icon:check[color: green]
|<<eureka>>
|*$PROJECT_HOME*/eureka
|Service Registry - https://github.com/Netflix/eureka/wiki/Eureka-at-a-glance

|icon:check[color: green]
|<<config-server>>
|*$PROJECT_HOME*/config-server
|Centralized Configuration Server - https://cloud.spring.io/spring-cloud-config/spring-cloud-config.html

|icon:check[color: green]
|<<zipkin-server>>
|*$PROJECT_HOME*/zipkin-server
| http://zipkin.io/[Distributed Tracing system]

|icon:check[color: green]
|<<zuul>>
|*$PROJECT_HOME*/zuul
| https://github.com/Netflix/zuul/wiki[Java based Proxy]

|icon:check[color: green]
|<<ingredients>>
|*$PROJECT_HOME*/ingredients
|

|icon:check[color: green]
|<<reporting>>
|*$PROJECT_HOME*/reporting
|

|icon:check[color: green]
|<<brewing>>
|*$PROJECT_HOME*/brewing
|

|icon:check[color: green]
|<<presenting>>
|*$PROJECT_HOME*/presenting
|

|===


[[itr1-build-app]]
=== Building

Brewery application uses gradle for build, we will leverage on the same to get the application artifacts ready. To build the applicaiton
run the following command

[source,sh]
----
./gradlew -DWHAT_TO_TEST="SLEUTH_STREAM" clean build <1>
./mvnw -N install <2>
----

<1> We will be using https://cloud.spring.io/spring-cloud-sleuth/[Spring Cloud Sleuth] for sending trace information to https://github.com/openzipkin/zipkin[Zipkin]
<2> This will install the brewery parent pom in local maven repository

[[itr1-deploy-to-openshift]]
=== Deploying to OpenShift

As part of this lift and shift of existing application, to make it work as-is, there is certain order of applicaiton deployment might be required.  The following section
explains the deployment of the application in the same order as expected  ( you can expriment with it if you like :) )

[[rabbitmq]]
==== RabbitMQ

Go to the directory  *$PROJECT_HOME/extras/rabbitmq*, and execute the following command

[source,sh]
----
./mvnw -Dfabric8.mode=kubernetes clean fabric8:deploy
----

This will take some time to get it running as the deployment needs to download the `rabbitmq` docker image

[[config-server]]
==== Config Server

Go to the directory  *$PROJECT_HOME/config-server*, and execute the following command

[source,sh]
----
./mvnw clean fabric8:deploy
----

NOTE: Since this is the first Java application to be deployed,  it may take some time to download the necessary images from docker hub.

[[eureka]]
==== Eureka

Go to the directory  *$PROJECT_HOME/eureka*, and execute the following command

[source,sh]
----
./mvnw clean fabric8:deploy
----

[[zipkin-server]]
==== Zipkin Server

Go to the directory  *$PROJECT_HOME/zipkin-server*, and execute the following command

[source,sh]
----
./mvnw clean fabric8:deploy
----

[[zuul]]
==== Zuul

Go to the directory  *$PROJECT_HOME/zuul*, and execute the following command

[source,sh]
----
./mvnw clean fabric8:deploy
----

[[ingredients]]
==== Ingredients

Go to the directory  *$PROJECT_HOME/ingredients*, and execute the following command

[source,sh]
----
./mvnw clean fabric8:deploy
----

[[reporting]]
==== Reporting

Go to the directory  *$PROJECT_HOME/reporting*, and execute the following command

[source,sh]
----
./mvnw clean fabric8:deploy
----

[[brewing]]
==== Brewing

Go to the directory  *$PROJECT_HOME/brewing*, and execute the following command

[source,sh]
----
./mvnw clean fabric8:deploy
----

[[presenting]]
==== Presenting

Go to the directory  *$PROJECT_HOME/presenting*, and execute the following command

[source,sh]
----
./mvnw clean fabric8:deploy
----