[[iteration-2]]
= Iteration II

The Iteration II will <<itr2-deprecated-modules,deprecate>> few of the https://netflix.github.io/[NetFlix OSS] components that are superflous
inside https://kubernetes.io[Kubernetes] or https://www.openshift.com[Openshift]. The following sections shows how to get
the Iteration II deployed on to https://kubernetes.io[Kubernetes] or https://www.openshift.com[Openshift]. This iteration
uses the https://github.com/spring-cloud-incubator/spring-cloud-kubernetes[Spring Cloud Kubernetes] -
the http://projects.spring.io/spring-cloud/[Spring Cloud] based discovery client for Kubernetes

[[itr2-application-setup]]
== Setup

[[itr2-clone-source]]
=== Clone

[source,sh]
----
git clone -b iteration-2 https://github.com/redhat-developer-demos/brewery.git
----

[NOTE]
====
Through out this document we will call the directoy where the project was cloned as _$PROJECT_HOME_
====


[[itr2-pre-req]]
== Pre-Requisite

[[itr2-pre-req-general]]
=== General
The spring-cloud-kubernetes library used in the project requires the `default` service account to have view permissions, to enable that we execute the following command,

[source,sh]
----
oc policy add-role-to-user view -z default -n $(oc project -q)
----


[[itr2-pre-req-rabbitmq]]
=== RabbitMQ 

The https://hub.docker.com/_/rabbitmq/[RabbimtMQ] container image when run is run using `root` user, which is restricted in OpenShift by defult, to enable the container to be run with `root` we need to give special permissions. 

We create a seperate service account called **brewery** and add the required SCC to it as shown below.

[source,sh]
----
oc adm policy add-scc-to-user privileged -z brewery <1>

oc adm policy add-scc-to-user anyuid -z brewery  <1>
----

<1> **brewery** service is created when RabbitMQ is deployed

More info on previleged access, refer https://docs.openshift.com/container-platform/3.5/admin_guide/manage_scc.html#grant-access-to-the-privileged-scc[here]


[[itr2-deployable-apps]]
== Deploy Applications

.Application List
[cols="1*^,1,1,5"]
|===
| |Application| Folder | Remarks

|icon:check[color: green]
|<<rabbitmq>>
|*$PROJECT_HOME*/extras/rabbitmq
|Message Broker - https://www.rabbitmq.com/

|icon:check[color: green]
|common
|*$PROJECT_HOME*/common
|Common shared library

|icon:check[color: green]
|common-zipkin-stream
|*$PROJECT_HOME*/ommon-zipkin-stream
|Common shared library for the projects that uses the Sleuth Zipkin Stream for tracing

|[red]#*X*#
|[red]#eureka#
|[red]#*$PROJECT_HOME*/eureka#
|Application will use https://kubernetes.io/docs/concepts/services-networking/service/[Kubernetes Services]

|[red]#*X*#
|[red]#config-server#
|[red]#*$PROJECT_HOME*/config-server#
|Application will use https://kubernetes.io/docs/tasks/configure-pod-container/configmap/[Kubernetes ConfigMaps]

|icon:check[color: green]
|<<zipkin-server>>
|*$PROJECT_HOME*/zipkin-server
| http://zipkin.io/[Distributed Tracing system]

|icon:check[color: green]
|<<zuul>>
|*$PROJECT_HOME*/zuul
| https://github.com/Netflix/zuul/wiki[Java based Proxy]

|icon:check[color: green]
|<<ingredients>>
|*$PROJECT_HOME*/ingredients
|

|icon:check[color: green]
|<<reporting>>
|*$PROJECT_HOME*/reporting
|

|icon:check[color: green]
|<<brewing>>
|*$PROJECT_HOME*/brewing
|

|icon:check[color: green]
|<<presenting>>
|*$PROJECT_HOME*/presenting
|

|===

[[itr2-build-app]]
=== Building

The Iteration II of the brewery application has migrated all the projects to http://maven.apache.org/[Apache Maven] based build,
to build the application run the following command

[source,sh]
----
./mvnw -N install <1>
./mvnw clean install <2>
----
<1> This will install the brewery parent pom in local maven repository
<2> This will build the applications, if the minishift or OpenShift cluster is running, this will trigger `s2i` builds
of the respective application as well

[[itr2-deploy-to-openshift]]
=== Deploying to OpenShift

As part of this lift and shift of existing application, to make it work as-is, there is certain order of applicaiton deployment might be required.  The following section
explains the deployment of the application in the same order as expected  ( you can expriment with it if you like :) )


[IMPORTANT]
====
Ensure that all <<itr2-pre-req,Pre-Requisite>> are done before starting deployment.
====

[[itr2-rabbitmq]]
==== RabbitMQ

[[itr2-rabbitmq-local]]
===== Local Deployment

Go to the directory  *$PROJECT_HOME/extras/rabbitmq*, and execute the following command

[source,sh]
----
./mvnw -Dfabric8.mode=kubernetes clean fabric8:deploy
----

[[itr2-rabbitmq-cloud]]
===== External Cloud Deployment

Sometimes you might have access to docker socket typical case when deploying to external cloud, in those cases you can run the following set of commands,

[source,sh]
----
./mvnw clean fabric8:resource
oc apply -f target/classes/META-INF/fabric8/openshift.yml
----

This will take some time to get it running as the deployment needs to download the `rabbitmq` docker image

[[itr2-zipkin-server]]
==== Zipkin Server

Go to the directory  *$PROJECT_HOME/zipkin-server*, and execute the following command

[source,sh]
----
./mvnw fabric8:deploy
----

[[zuul]]
==== Zuul

Go to the directory  *$PROJECT_HOME/zuul*, and execute the following command

[source,sh]
----
./mvnw fabric8:deploy
----

[[itr2-ingredients]]
==== Ingredients

Go to the directory  *$PROJECT_HOME/ingredients*, and execute the following command

[source,sh]
----
./mvnw fabric8:deploy
----

[[itr2-reporting]]
==== Reporting

Go to the directory  *$PROJECT_HOME/reporting*, and execute the following command

[source,sh]
----
./mvnw fabric8:deploy
----

[[itr2-brewing]]
==== Brewing

Go to the directory  *$PROJECT_HOME/brewing*, and execute the following command

[source,sh]
----
./mvnw fabric8:deploy
----

[[itr2-presenting]]
==== Presenting

Go to the directory  *$PROJECT_HOME/presenting*, and execute the following command

[source,sh]
----
./mvnw fabric8:deploy
----

[[itr2-acceptance-testing]]
== Acceptance Testing

The *$PROJECT_HOME/acceptance-tests* holds the test cases for testing the application.  To perform
we need to have have some ports forwarded from Kubernetes/OpenShift to localhost(where you build the application)

[source,sh]
----
oc port-forward zipkin-1-06wmt 9411:8080 <1>
oc port-forward presenting-1-wzhfn 9991:8080 <2>
----

<1> forward port 8080 from Zipkin pod to listen on localhost:9411
<2> forward port 8080 from Presenting pod to listen on localhost:9991

NOTE: Please update the pod names based on your local deployment

To run acceptance testing, execute following command from $PROJECT_HOME,

[source,sh]
----
 ./mvnw clean test
----

[[itr2-deprecated-modules]]

== Deprecated Modules

As part of Iteration-II the following modules have been deprecated,

* Eureka
* Config Server
* common-zipkin
* common-zipkin-old
* zookeeper
* docker
