[[res-tools]]
== Tools 

There are two main tools that is always used with Spring Boot on OpenShift

* https://developers.redhat.com/products/cdk/download/[RedHat Container Development Kit]
* https://maven.fabric8.io[fabric8 maven plugin]

You can also find related tools and downloads from https://developers.redhat.com

This page lists some commonly used commands, tips/tricks and some trouble shooting tips
around these tools.

[NOTE]
=====
This is not meant to replace original setup guide, please refer to the original setup guides
for detailed setup of these tools.
=====

=== Minishift

[source,sh]
----
oc login --server <your openshift master server url> -u developer 
----
Logging into OpenShift from cli using the user developer and the default password is developer.

[source,sh]
----
eval $(minishift oc-env)
----
Sets the right path to the OpenShift cli

[source,sh]
----
minishift console
----
Opens the OpenShift web console in the default browser

=== fabric8 maven plugin

[source,sh]
----
eval $(minishift docker-env)
----
This is very important command that you need to run before the first maven build, as this allows setting
some important docker variables

[source,sh]
----
mvn io.fabric8:fabric8-maven-plugin:3.5.30:setup
----
Sets up the fabric8 maven plugin in the current maven project.

NOTE: In the above code 3.5.30 is used as version, please update to version that suits your needs

[source,sh]
----
mvn fabric8:deploy
----
Deploys the current maven project into OpenShift

[source,sh]
----
mvn fabric8:undeploy
----
Deploys the current maven project from OpenShift

[source,sh]
----
mvn fabric8:debug
----
Setups up port forward to debug the current OpenShift project

[source,sh]
----
mvn fabric8:run
----
Quick deploy the current maven project to OpenShift, runs in foreground
and undeploys once CTRL + C is used to terminate current process in foreground.